#ifndef ___ENUMERATIONS

#define ___ENUMERATIONS

enum {
  OPERATION_MODE_NORMAL     = 0,
  OPERATION_MODE_BSP_INPUT  = 1,
  OPERATION_MODE_IPS_OUTPUT = 2
};

enum {
  DIRECTION_SOURCE        = 0,
  DIRECTION_SOURCE_TARGET = 1,
  DIRECTION_TARGET        = 2
};

enum {
  TARGET_TYPE_PREVIOUS    = 0xffffff,
  TARGET_TYPE_FROM_SOURCE = 0xfffffe
};

enum {
  VALIDATE_ALL    = 0,
  VALIDATE_LENGTH = 1,
  VALIDATE_NONE   = 2
};

enum {
  EXIT_STATUS_OK = 0,
  EXIT_STATUS_INVALID_OPTIONS = 1,
  EXIT_STATUS_ERROR = 2
};

enum {
  CODE_ERROR_INVALID_SOURCE = 1,
  CODE_ERROR_SOURCE_EQUALS_TARGET = 2,
  CODE_ERROR_INVALID_OUTPUT_SIZE = 3,
  CODE_ERROR_INVALID_OUTPUT_HASH = 4
};

#endif
