#include "proto.h"

char * generate_patch_code (Options options, CodeFile codefile) {
  builder_memory_region = create_memory_region();
  initialize_builder_state(options, codefile);
  builder_error = NULL;
  int rv = setjmp(builder_return_point);
  if (!rv) {
    add_version_header_comments();
    initialize_code_generator();
    generate_runtime();
    generate_patch_data();
    add_comment_to_codefile(builder_state -> codefile, "*******************************************************************************", 0);
    destroy_builder_state();
  }
  destroy_memory_region(builder_memory_region);
  return builder_error;
}

void builder_throw (const char * error, ...) {
  va_list ap;
  va_start(ap, error);
  builder_error = generate_string_from_varargs(error, ap);
  va_end(ap);
  longjmp(builder_return_point, 1);
}

void add_version_header_comments (void) {
  add_comment_to_codefile(builder_state -> codefile, "*******************************************************************************", 0);
  add_comment_to_codefile(builder_state -> codefile, "patch autogenerated by bspbuild " VERSION_STRING, 0);
  add_blank_line_to_codefile(builder_state -> codefile);
}

void destroy_builder_state (void) {
  mr_free(builder_memory_region, builder_state -> file_data);
  mr_free(builder_memory_region, builder_state -> file_name_labels);
  mr_free(builder_memory_region, builder_state);
  builder_state = NULL;
}
